services:
  fe-smarttasty:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: https://api.smart-tasty.io.vn
        NEXT_PUBLIC_WEBSOCKET_URL: https://socket.smart-tasty.io.vn
        NEXT_PUBLIC_ENV: production
    container_name: ${FE_CONTAINER_NAME}
    ports:
      - "${FE_PORT}:3000"
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV} # runtime

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-fe
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}
      - DOCKER_HUB_PASSWORD=${DOCKER_HUB_ACCESS_TOKEN}
    command: --interval ${WATCHTOWER_INTERVAL} # Checks for updates
